version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: careercoach-db
    environment:
      POSTGRES_DB: careercoach_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./careercoach-backend
      dockerfile: Dockerfile
    container_name: careercoach-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/careercoach_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=b6540c9d7a2245b630b9101b447608b4938a902df595b16952cc1d84813589b9
      - JWT_EXPIRATION=86400000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_API_URL=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./careercoach-frontend
      dockerfile: Dockerfile
    container_name: careercoach-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
